users_index:
    path:     /
    defaults: { _controller: "AppBundle:Users:index" }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Users:show" }
    methods:  GET



users_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Users:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Users:delete" }
    methods:  DELETE
